[0m13:32:45.434098 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D74DE6160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D777EDE50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D777CF3A0>]}


============================== 13:32:45.438397 | 95758be0-541c-4bf7-aa68-ff00cc051a95 ==============================
[0m13:32:45.438397 [info ] [MainThread]: Running with dbt=1.7.9
[0m13:32:45.439410 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\jrver\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:32:57.733872 [debug] [MainThread]: Starter project path: C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\include\starter_project
[0m13:32:57.747694 [info ] [MainThread]: 
Your new dbt project "dbt_bigquery" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:32:57.748641 [info ] [MainThread]: Setting up your profile.
[0m13:38:33.233558 [info ] [MainThread]: Profile dbt_bigquery written to C:\Users\jrver\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:38:33.235863 [debug] [MainThread]: Command `dbt init` succeeded at 13:38:33.235863 after 347.87 seconds
[0m13:38:33.235863 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D74DE6160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D77817490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D77817E50>]}
[0m13:38:33.236960 [debug] [MainThread]: Flushing usage events
[0m13:40:07.090299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001875442B7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018756E37790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018756E37EE0>]}


============================== 13:40:07.093688 | c8dfd056-be7c-42e8-b28e-a6d6e8c27cdc ==============================
[0m13:40:07.093688 [info ] [MainThread]: Running with dbt=1.7.9
[0m13:40:07.094808 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jrver\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt-BigQuery', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:40:58.806087 [error] [MainThread]: Encountered an error:

[0m13:40:58.808248 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\task\init.py", line 322, in run
    project_name = self.get_valid_project_name()
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\dbt\task\init.py", line 276, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\venv\lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m13:40:58.810552 [debug] [MainThread]: Command `dbt init` failed at 13:40:58.810407 after 51.79 seconds
[0m13:40:58.810552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001875442B7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018756E69370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018756E69550>]}
[0m13:40:58.811625 [debug] [MainThread]: Flushing usage events
[0m13:41:06.946339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021717A269D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002171A427D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002171A427CD0>]}


============================== 13:41:06.951689 | 99f707f6-e965-4492-b3b8-5599682a813f ==============================
[0m13:41:06.951689 [info ] [MainThread]: Running with dbt=1.7.9
[0m13:41:06.952768 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jrver\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_bigquery', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:41:06.953776 [info ] [MainThread]: A project called dbt_bigquery already exists here.
[0m13:41:06.954829 [debug] [MainThread]: Command `dbt init` succeeded at 13:41:06.954829 after 0.07 seconds
[0m13:41:06.955655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021717A269D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002171A42EF70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002171A427F70>]}
[0m13:41:06.956559 [debug] [MainThread]: Flushing usage events
[0m13:41:56.434759 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028688EF7400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002868B9021C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002868B902AF0>]}


============================== 13:41:56.439119 | 4f4f1276-2602-4eae-8042-0db3d323e89f ==============================
[0m13:41:56.439119 [info ] [MainThread]: Running with dbt=1.7.9
[0m13:41:56.440204 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\jrver\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:41:56.440260 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jrver\PycharmProjects\Python\K8s-dbt-GCP\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:41:56.441335 [debug] [MainThread]: Command `dbt run` failed at 13:41:56.441335 after 0.06 seconds
[0m13:41:56.442439 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028688EF7400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002868B9021C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002868B902AC0>]}
[0m13:41:56.442439 [debug] [MainThread]: Flushing usage events
